###
# Авторизация
POST http://localhost:8000/api/token/
Content-Type:application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###
# Обновление токена
POST http://localhost:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "{{refresh_token}}"
}