# Generated by Django 4.1.6 on 2023-06-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceuser',
            options={'ordering': ('id',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
