# Generated by Django 4.1.6 on 2023-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_control_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('1', 'Не начато'), ('2', 'В работе'), ('3', 'Выполнено')], max_length=1024, verbose_name='Статус'),
        ),
    ]
